blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/tabibhasann/qgis-layer-diff/discussions
    about: Ask questions and share ideas in Discussions
  - name: Security Reports
    url: https://github.com/tabibhasann/qgis-layer-diff/security/advisories/new
    about: Report security vulnerabilities privately
